// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuhsbvtmzyfcookhlxdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1aHNidnRtenlmY29va2hseGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTk0NDQsImV4cCI6MjA2MjEzNTQ0NH0.hi8XXAez4MtMOP0uafflyEW1jOC9xgN1gTFGGEIOFgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);